/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SmsOptInRouteImport } from './routes/sms-opt-in'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVapiRouteImport } from './routes/_authenticated/vapi'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedSchedulingRouteImport } from './routes/_authenticated/scheduling'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicSmsOptInRouteImport } from './routes/api/public/sms-opt-in'
import { Route as ApiMobileTestPushRouteImport } from './routes/api/mobile/test-push'
import { Route as ApiMobileSendSmsRouteImport } from './routes/api/mobile/send-sms'
import { Route as ApiMobileRecordingUrlRouteImport } from './routes/api/mobile/recording-url'
import { Route as ApiMobilePushTokenRouteImport } from './routes/api/mobile/push-token'
import { Route as ApiMobileForwardingStatusRouteImport } from './routes/api/mobile/forwarding-status'
import { Route as ApiPublicVapiWebhookRouteImport } from './routes/api/public/vapi/webhook'
import { Route as ApiPublicTwilioSmsInboundRouteImport } from './routes/api/public/twilio/sms-inbound'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsOptInRoute = SmsOptInRouteImport.update({
  id: '/sms-opt-in',
  path: '/sms-opt-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVapiRoute = AuthenticatedVapiRouteImport.update({
  id: '/vapi',
  path: '/vapi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulingRoute = AuthenticatedSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSmsOptInRoute = ApiPublicSmsOptInRouteImport.update({
  id: '/api/public/sms-opt-in',
  path: '/api/public/sms-opt-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileTestPushRoute = ApiMobileTestPushRouteImport.update({
  id: '/api/mobile/test-push',
  path: '/api/mobile/test-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSendSmsRoute = ApiMobileSendSmsRouteImport.update({
  id: '/api/mobile/send-sms',
  path: '/api/mobile/send-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileRecordingUrlRoute = ApiMobileRecordingUrlRouteImport.update({
  id: '/api/mobile/recording-url',
  path: '/api/mobile/recording-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePushTokenRoute = ApiMobilePushTokenRouteImport.update({
  id: '/api/mobile/push-token',
  path: '/api/mobile/push-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileForwardingStatusRoute =
  ApiMobileForwardingStatusRouteImport.update({
    id: '/api/mobile/forwarding-status',
    path: '/api/mobile/forwarding-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVapiWebhookRoute = ApiPublicVapiWebhookRouteImport.update({
  id: '/api/public/vapi/webhook',
  path: '/api/public/vapi/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsInboundRoute =
  ApiPublicTwilioSmsInboundRouteImport.update({
    id: '/api/public/twilio/sms-inbound',
    path: '/api/public/twilio/sms-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/vapi': typeof AuthenticatedVapiRoute
  '/api/mobile/forwarding-status': typeof ApiMobileForwardingStatusRoute
  '/api/mobile/push-token': typeof ApiMobilePushTokenRoute
  '/api/mobile/recording-url': typeof ApiMobileRecordingUrlRoute
  '/api/mobile/send-sms': typeof ApiMobileSendSmsRoute
  '/api/mobile/test-push': typeof ApiMobileTestPushRoute
  '/api/public/sms-opt-in': typeof ApiPublicSmsOptInRoute
  '/api/public/twilio/sms-inbound': typeof ApiPublicTwilioSmsInboundRoute
  '/api/public/vapi/webhook': typeof ApiPublicVapiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/vapi': typeof AuthenticatedVapiRoute
  '/api/mobile/forwarding-status': typeof ApiMobileForwardingStatusRoute
  '/api/mobile/push-token': typeof ApiMobilePushTokenRoute
  '/api/mobile/recording-url': typeof ApiMobileRecordingUrlRoute
  '/api/mobile/send-sms': typeof ApiMobileSendSmsRoute
  '/api/mobile/test-push': typeof ApiMobileTestPushRoute
  '/api/public/sms-opt-in': typeof ApiPublicSmsOptInRoute
  '/api/public/twilio/sms-inbound': typeof ApiPublicTwilioSmsInboundRoute
  '/api/public/vapi/webhook': typeof ApiPublicVapiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/scheduling': typeof AuthenticatedSchedulingRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/vapi': typeof AuthenticatedVapiRoute
  '/api/mobile/forwarding-status': typeof ApiMobileForwardingStatusRoute
  '/api/mobile/push-token': typeof ApiMobilePushTokenRoute
  '/api/mobile/recording-url': typeof ApiMobileRecordingUrlRoute
  '/api/mobile/send-sms': typeof ApiMobileSendSmsRoute
  '/api/mobile/test-push': typeof ApiMobileTestPushRoute
  '/api/public/sms-opt-in': typeof ApiPublicSmsOptInRoute
  '/api/public/twilio/sms-inbound': typeof ApiPublicTwilioSmsInboundRoute
  '/api/public/vapi/webhook': typeof ApiPublicVapiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/sms-opt-in'
    | '/terms'
    | '/terms-and-conditions'
    | '/terms-of-service'
    | '/tos'
    | '/dashboard'
    | '/revenue'
    | '/scheduling'
    | '/scripts'
    | '/settings'
    | '/team'
    | '/vapi'
    | '/api/mobile/forwarding-status'
    | '/api/mobile/push-token'
    | '/api/mobile/recording-url'
    | '/api/mobile/send-sms'
    | '/api/mobile/test-push'
    | '/api/public/sms-opt-in'
    | '/api/public/twilio/sms-inbound'
    | '/api/public/vapi/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/sms-opt-in'
    | '/terms'
    | '/terms-and-conditions'
    | '/terms-of-service'
    | '/tos'
    | '/dashboard'
    | '/revenue'
    | '/scheduling'
    | '/scripts'
    | '/settings'
    | '/team'
    | '/vapi'
    | '/api/mobile/forwarding-status'
    | '/api/mobile/push-token'
    | '/api/mobile/recording-url'
    | '/api/mobile/send-sms'
    | '/api/mobile/test-push'
    | '/api/public/sms-opt-in'
    | '/api/public/twilio/sms-inbound'
    | '/api/public/vapi/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/compliance'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/sms-opt-in'
    | '/terms'
    | '/terms-and-conditions'
    | '/terms-of-service'
    | '/tos'
    | '/_authenticated/dashboard'
    | '/_authenticated/revenue'
    | '/_authenticated/scheduling'
    | '/_authenticated/scripts'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/vapi'
    | '/api/mobile/forwarding-status'
    | '/api/mobile/push-token'
    | '/api/mobile/recording-url'
    | '/api/mobile/send-sms'
    | '/api/mobile/test-push'
    | '/api/public/sms-opt-in'
    | '/api/public/twilio/sms-inbound'
    | '/api/public/vapi/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SmsOptInRoute: typeof SmsOptInRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TosRoute: typeof TosRoute
  ApiMobileForwardingStatusRoute: typeof ApiMobileForwardingStatusRoute
  ApiMobilePushTokenRoute: typeof ApiMobilePushTokenRoute
  ApiMobileRecordingUrlRoute: typeof ApiMobileRecordingUrlRoute
  ApiMobileSendSmsRoute: typeof ApiMobileSendSmsRoute
  ApiMobileTestPushRoute: typeof ApiMobileTestPushRoute
  ApiPublicSmsOptInRoute: typeof ApiPublicSmsOptInRoute
  ApiPublicTwilioSmsInboundRoute: typeof ApiPublicTwilioSmsInboundRoute
  ApiPublicVapiWebhookRoute: typeof ApiPublicVapiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-opt-in': {
      id: '/sms-opt-in'
      path: '/sms-opt-in'
      fullPath: '/sms-opt-in'
      preLoaderRoute: typeof SmsOptInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vapi': {
      id: '/_authenticated/vapi'
      path: '/vapi'
      fullPath: '/vapi'
      preLoaderRoute: typeof AuthenticatedVapiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scheduling': {
      id: '/_authenticated/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof AuthenticatedSchedulingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sms-opt-in': {
      id: '/api/public/sms-opt-in'
      path: '/api/public/sms-opt-in'
      fullPath: '/api/public/sms-opt-in'
      preLoaderRoute: typeof ApiPublicSmsOptInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/test-push': {
      id: '/api/mobile/test-push'
      path: '/api/mobile/test-push'
      fullPath: '/api/mobile/test-push'
      preLoaderRoute: typeof ApiMobileTestPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/send-sms': {
      id: '/api/mobile/send-sms'
      path: '/api/mobile/send-sms'
      fullPath: '/api/mobile/send-sms'
      preLoaderRoute: typeof ApiMobileSendSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/recording-url': {
      id: '/api/mobile/recording-url'
      path: '/api/mobile/recording-url'
      fullPath: '/api/mobile/recording-url'
      preLoaderRoute: typeof ApiMobileRecordingUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/push-token': {
      id: '/api/mobile/push-token'
      path: '/api/mobile/push-token'
      fullPath: '/api/mobile/push-token'
      preLoaderRoute: typeof ApiMobilePushTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/forwarding-status': {
      id: '/api/mobile/forwarding-status'
      path: '/api/mobile/forwarding-status'
      fullPath: '/api/mobile/forwarding-status'
      preLoaderRoute: typeof ApiMobileForwardingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vapi/webhook': {
      id: '/api/public/vapi/webhook'
      path: '/api/public/vapi/webhook'
      fullPath: '/api/public/vapi/webhook'
      preLoaderRoute: typeof ApiPublicVapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms-inbound': {
      id: '/api/public/twilio/sms-inbound'
      path: '/api/public/twilio/sms-inbound'
      fullPath: '/api/public/twilio/sms-inbound'
      preLoaderRoute: typeof ApiPublicTwilioSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSchedulingRoute: typeof AuthenticatedSchedulingRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedVapiRoute: typeof AuthenticatedVapiRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSchedulingRoute: AuthenticatedSchedulingRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedVapiRoute: AuthenticatedVapiRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SmsOptInRoute: SmsOptInRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TosRoute: TosRoute,
  ApiMobileForwardingStatusRoute: ApiMobileForwardingStatusRoute,
  ApiMobilePushTokenRoute: ApiMobilePushTokenRoute,
  ApiMobileRecordingUrlRoute: ApiMobileRecordingUrlRoute,
  ApiMobileSendSmsRoute: ApiMobileSendSmsRoute,
  ApiMobileTestPushRoute: ApiMobileTestPushRoute,
  ApiPublicSmsOptInRoute: ApiPublicSmsOptInRoute,
  ApiPublicTwilioSmsInboundRoute: ApiPublicTwilioSmsInboundRoute,
  ApiPublicVapiWebhookRoute: ApiPublicVapiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
