/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SmsOptInRouteImport } from './routes/sms-opt-in'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoiceTestRouteImport } from './routes/_authenticated/voice-test'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicSmsOptInRouteImport } from './routes/api/public/sms-opt-in'
import { Route as ApiPublicTwilioSmsInboundRouteImport } from './routes/api/public/twilio/sms-inbound'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsOptInRoute = SmsOptInRouteImport.update({
  id: '/sms-opt-in',
  path: '/sms-opt-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceTestRoute = AuthenticatedVoiceTestRouteImport.update({
  id: '/voice-test',
  path: '/voice-test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSmsOptInRoute = ApiPublicSmsOptInRouteImport.update({
  id: '/api/public/sms-opt-in',
  path: '/api/public/sms-opt-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsInboundRoute =
  ApiPublicTwilioSmsInboundRouteImport.update({
    id: '/api/public/twilio/sms-inbound',
    path: '/api/public/twilio/sms-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/voice-test': typeof AuthenticatedVoiceTestRoute
  '/api/public/sms-opt-in': typeof ApiPublicSmsOptInRoute
  '/api/public/twilio/sms-inbound': typeof ApiPublicTwilioSmsInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/voice-test': typeof AuthenticatedVoiceTestRoute
  '/api/public/sms-opt-in': typeof ApiPublicSmsOptInRoute
  '/api/public/twilio/sms-inbound': typeof ApiPublicTwilioSmsInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/voice-test': typeof AuthenticatedVoiceTestRoute
  '/api/public/sms-opt-in': typeof ApiPublicSmsOptInRoute
  '/api/public/twilio/sms-inbound': typeof ApiPublicTwilioSmsInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/signup'
    | '/sms-opt-in'
    | '/terms'
    | '/terms-and-conditions'
    | '/terms-of-service'
    | '/tos'
    | '/dashboard'
    | '/revenue'
    | '/settings'
    | '/team'
    | '/voice-test'
    | '/api/public/sms-opt-in'
    | '/api/public/twilio/sms-inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/signup'
    | '/sms-opt-in'
    | '/terms'
    | '/terms-and-conditions'
    | '/terms-of-service'
    | '/tos'
    | '/dashboard'
    | '/revenue'
    | '/settings'
    | '/team'
    | '/voice-test'
    | '/api/public/sms-opt-in'
    | '/api/public/twilio/sms-inbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/compliance'
    | '/cookies'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/privacy-policy'
    | '/signup'
    | '/sms-opt-in'
    | '/terms'
    | '/terms-and-conditions'
    | '/terms-of-service'
    | '/tos'
    | '/_authenticated/dashboard'
    | '/_authenticated/revenue'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/voice-test'
    | '/api/public/sms-opt-in'
    | '/api/public/twilio/sms-inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignupRoute: typeof SignupRoute
  SmsOptInRoute: typeof SmsOptInRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TosRoute: typeof TosRoute
  ApiPublicSmsOptInRoute: typeof ApiPublicSmsOptInRoute
  ApiPublicTwilioSmsInboundRoute: typeof ApiPublicTwilioSmsInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-opt-in': {
      id: '/sms-opt-in'
      path: '/sms-opt-in'
      fullPath: '/sms-opt-in'
      preLoaderRoute: typeof SmsOptInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice-test': {
      id: '/_authenticated/voice-test'
      path: '/voice-test'
      fullPath: '/voice-test'
      preLoaderRoute: typeof AuthenticatedVoiceTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sms-opt-in': {
      id: '/api/public/sms-opt-in'
      path: '/api/public/sms-opt-in'
      fullPath: '/api/public/sms-opt-in'
      preLoaderRoute: typeof ApiPublicSmsOptInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms-inbound': {
      id: '/api/public/twilio/sms-inbound'
      path: '/api/public/twilio/sms-inbound'
      fullPath: '/api/public/twilio/sms-inbound'
      preLoaderRoute: typeof ApiPublicTwilioSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedVoiceTestRoute: typeof AuthenticatedVoiceTestRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedVoiceTestRoute: AuthenticatedVoiceTestRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignupRoute: SignupRoute,
  SmsOptInRoute: SmsOptInRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TosRoute: TosRoute,
  ApiPublicSmsOptInRoute: ApiPublicSmsOptInRoute,
  ApiPublicTwilioSmsInboundRoute: ApiPublicTwilioSmsInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
